-- AlterTable
ALTER TABLE "Chat" ADD COLUMN     "room_id" INTEGER NOT NULL DEFAULT 1;

-- AddForeignKey
ALTER TABLE "Chat" ADD CONSTRAINT "Chat_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "Room"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
